# palette = "catppuccin_macchiato"
add_newline = true
palette = "catppuccin_mocha"

right_format="""
$time"""

# Inserts a blank line between shell prompts
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#c6aae8"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"


# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[‚ûú](bold green)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
error_symbol = "[‚ûú]](bold red)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
# ü•∑üèª
# success_symbol = "[ü•∑](bold green)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
# success_symbol = "[üêá](bold green)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
# success_symbol = "[‚û¢ ](bold blue)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
# error_symbol = "[ü§Æ ](bold red)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"

[cmd_duration]
min_time = 1_000

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[directory]
# truncate_length = how many directories deep before path is truncated
truncation_length = 2
truncate_to_repo = false
# format = "[$path]($style)[$lock_symbol]($lock_style) "
format = "[$path]($style)[$read_only]($read_only_style) "
style ="bold lavender"

# [memory_usage]
# format = '\[$symbol[$ram( | $swap)]($style)\]'

[git_branch]
# symbol = "[Óôù ](blue)"
# symbol = "[Óú• ](blue)"
# symbol = "[Ôêò ](blue)"
symbol = "[Óú• ](rosewater)"
format = '[$symbol$branch]($style)'

[git_status]
# up_to_date = "[‚úì](bold green)"
stashed = ""
ahead = "[‚á°](blue)${count}"
# staged = '[++\($count\)](green)'
staged = '[++\($count\)](green)'
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "[‚á£](blue)${count}"
format = '([$all_status$ahead_behind]($style))'

[git_commit]
commit_hash_length = 8
style = "bold white"

[golang]
symbol = "[Óòß](cyan)"
format = '[$symbol]($style) Go '

[python]
symbol = "[Óúº](green)"
format = '[${symbol}${pyenv_prefix} (${virtualenv})]($style) '

# [lua]
# disabled = true
# symbol = "[Óò† ](blue)"


[custom.tmux]
symbol = "üêá()"
when = "[ ! -z $TMUX ]"
format = '        [${symbol}]($style) '

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[bun]
format = " [$symbol]($style)"

[buf]
format = " [$symbol]($style)"

[cmake]
format = " [$symbol]($style)"

[cobol]
format = " [$symbol]($style)"

[crystal]
format = " [$symbol]($style)"

[daml]
format = " [$symbol]($style)"

[dart]
format = " [$symbol]($style)"

[deno]
format = " [$symbol]($style)"

[dotnet]
format = "[$symbol(üéØ $tfm )]($style)"

[elixir]
format = ' [$symbol]($style)'

[elm]
format = ' [$symbol]($style)'

[erlang]
format = ' [$symbol]($style)'

[fennel]
format = ' [$symbol]($style)'

[gradle]
format = ' [$symbol]($style)'

[haxe]
format = ' [$symbol]($style)'

[helm]
format = ' [$symbol]($style)'

[java]
format = ' [$symbol]($style)'

[julia]
format = ' [$symbol]($style)'

[kotlin]
format = ' [$symbol]($style)'

[lua]
format = ' [$symbol]($style)'

[meson]
format = ' [$symbol]($style)'

[nim]
format = ' [$symbol]($style)'

[nodejs]
format = ' [$symbol]($style)'

[ocaml]
format = ' [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = ' [$symbol]($style)'

[perl]
format = ' [$symbol]($style)'

[php]
format = ' [$symbol]($style)'

[pulumi]
format = ' [$symbol$stack]($style)'

[purescript]
format = ' [$symbol]($style)'

[raku]
format = ' [$symbol]($style)'

[red]
format = ' [$symbol]($style)'

[rlang]
format = ' [$symbol]($style)'

[ruby]
format = ' [$symbol]($style)'

[rust]
format = ' [$symbol]($style)'

[solidity]
format = ' [$symbol]($style)'

[swift]
format = ' [$symbol]($style)'

[vagrant]
format = ' [$symbol]($style)'

[vlang]
format = ' [$symbol]($style)'

[zig]
format = ' [$symbol]($style)'
