palette = "catppuccin_macchiato"

# Inserts a blank line between shell prompts
add_newline = true

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# ğŸ¥·ğŸ»
# success_symbol = "[ğŸ¥·](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# success_symbol = "[ğŸ‡](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# success_symbol = "[â¢ ](bold blue)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# error_symbol = "[ğŸ¤® ](bold red)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[cmd_duration]
min_time = 1_000

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[git_branch]
symbol = "[ï‡’](blue)"
format = '[$symbol $branch]($style)'

[git_status]
# up_to_date = "[âœ“](bold green)"
stashed = ""
ahead = "[â‡¡](blue)${count}"
staged = '[++\($count\)](green)'
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "[â‡£](blue)${count}"
format = '( [$all_status$ahead_behind]($style)) '

[golang]
symbol = "[î˜§](cyan)"
format = ' Go[ $symbol ]($style)'

[python]
# format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '
symbol = "[îœ¼](green)"
# format = '\[[${symbol}${pyenv_prefix} (\($virtualenv\))]($style)\] '
format = ' [${symbol}${pyenv_prefix} ($virtualenv)]($style) '

[lua]
disabled = true
symbol = "[î˜  ](blue)"

# [custom.tmux]
# # function is_tmux() in zshrc
# # command = 'echo $TERM | cut -d"-" -f1'
# command = 'echo $TERM'
# symbol = "[ï’‰](red)"
# when = "true"
# format = '| [${symbol}${output}]($style) '
